package hla.rti1516_2025.exceptions;

/*
 * Runtime declarations for the standard exception names not separately used
 * by the fixture's compile-time method signatures.  The production bridge is
 * built against a real standard Java API JAR, where each name is public in
 * its own source file.  These package-local classes let JNI preserve the
 * exact C++ exception name in fixture-based C++ -> Java -> JPype tests.
 */
class AsynchronousDeliveryAlreadyDisabled extends RTIexception { AsynchronousDeliveryAlreadyDisabled(String message) { super(message); } }
class AsynchronousDeliveryAlreadyEnabled extends RTIexception { AsynchronousDeliveryAlreadyEnabled(String message) { super(message); } }
class AttributeAcquisitionWasNotRequested extends RTIexception { AttributeAcquisitionWasNotRequested(String message) { super(message); } }
class AttributeAlreadyBeingAcquired extends RTIexception { AttributeAlreadyBeingAcquired(String message) { super(message); } }
class AttributeAlreadyBeingChanged extends RTIexception { AttributeAlreadyBeingChanged(String message) { super(message); } }
class AttributeAlreadyBeingDivested extends RTIexception { AttributeAlreadyBeingDivested(String message) { super(message); } }
class AttributeAlreadyOwned extends RTIexception { AttributeAlreadyOwned(String message) { super(message); } }
class AttributeDivestitureWasNotRequested extends RTIexception { AttributeDivestitureWasNotRequested(String message) { super(message); } }
class AttributeNotDefined extends RTIexception { AttributeNotDefined(String message) { super(message); } }
class AttributeNotOwned extends RTIexception { AttributeNotOwned(String message) { super(message); } }
class AttributeNotPublished extends RTIexception { AttributeNotPublished(String message) { super(message); } }
class AttributeRelevanceAdvisorySwitchIsOff extends RTIexception { AttributeRelevanceAdvisorySwitchIsOff(String message) { super(message); } }
class AttributeRelevanceAdvisorySwitchIsOn extends RTIexception { AttributeRelevanceAdvisorySwitchIsOn(String message) { super(message); } }
class AttributeScopeAdvisorySwitchIsOff extends RTIexception { AttributeScopeAdvisorySwitchIsOff(String message) { super(message); } }
class AttributeScopeAdvisorySwitchIsOn extends RTIexception { AttributeScopeAdvisorySwitchIsOn(String message) { super(message); } }
class CallNotAllowedFromWithinCallback extends RTIexception { CallNotAllowedFromWithinCallback(String message) { super(message); } }
class ConnectionFailed extends RTIexception { ConnectionFailed(String message) { super(message); } }
class CouldNotCreateLogicalTimeFactory extends RTIexception { CouldNotCreateLogicalTimeFactory(String message) { super(message); } }
class CouldNotDecode extends RTIexception { CouldNotDecode(String message) { super(message); } }
class CouldNotEncode extends RTIexception { CouldNotEncode(String message) { super(message); } }
class CouldNotOpenFOM extends RTIexception { CouldNotOpenFOM(String message) { super(message); } }
class CouldNotOpenMIM extends RTIexception { CouldNotOpenMIM(String message) { super(message); } }
class DeletePrivilegeNotHeld extends RTIexception { DeletePrivilegeNotHeld(String message) { super(message); } }
class DesignatorIsHLAstandardMIM extends RTIexception { DesignatorIsHLAstandardMIM(String message) { super(message); } }
class ErrorReadingFOM extends RTIexception { ErrorReadingFOM(String message) { super(message); } }
class ErrorReadingMIM extends RTIexception { ErrorReadingMIM(String message) { super(message); } }
class FederateAlreadyExecutionMember extends RTIexception { FederateAlreadyExecutionMember(String message) { super(message); } }
class FederateHandleNotKnown extends RTIexception { FederateHandleNotKnown(String message) { super(message); } }
class FederateHasNotBegunSave extends RTIexception { FederateHasNotBegunSave(String message) { super(message); } }
class FederateInternalError extends RTIexception { FederateInternalError(String message) { super(message); } }
class FederateIsExecutionMember extends RTIexception { FederateIsExecutionMember(String message) { super(message); } }
class FederateNameAlreadyInUse extends RTIexception { FederateNameAlreadyInUse(String message) { super(message); } }
class FederateOwnsAttributes extends RTIexception { FederateOwnsAttributes(String message) { super(message); } }
class FederateServiceInvocationsAreBeingReportedViaMOM extends RTIexception { FederateServiceInvocationsAreBeingReportedViaMOM(String message) { super(message); } }
class FederateUnableToUseTime extends RTIexception { FederateUnableToUseTime(String message) { super(message); } }
class FederatesCurrentlyJoined extends RTIexception { FederatesCurrentlyJoined(String message) { super(message); } }
class FederationExecutionAlreadyExists extends RTIexception { FederationExecutionAlreadyExists(String message) { super(message); } }
class FederationExecutionDoesNotExist extends RTIexception { FederationExecutionDoesNotExist(String message) { super(message); } }
class IllegalName extends RTIexception { IllegalName(String message) { super(message); } }
class IllegalTimeArithmetic extends RTIexception { IllegalTimeArithmetic(String message) { super(message); } }
class InconsistentFOM extends RTIexception { InconsistentFOM(String message) { super(message); } }
class InteractionClassAlreadyBeingChanged extends RTIexception { InteractionClassAlreadyBeingChanged(String message) { super(message); } }
class InteractionClassNotDefined extends RTIexception { InteractionClassNotDefined(String message) { super(message); } }
class InteractionClassNotPublished extends RTIexception { InteractionClassNotPublished(String message) { super(message); } }
class InteractionParameterNotDefined extends RTIexception { InteractionParameterNotDefined(String message) { super(message); } }
class InteractionRelevanceAdvisorySwitchIsOff extends RTIexception { InteractionRelevanceAdvisorySwitchIsOff(String message) { super(message); } }
class InteractionRelevanceAdvisorySwitchIsOn extends RTIexception { InteractionRelevanceAdvisorySwitchIsOn(String message) { super(message); } }
class InternalError extends RTIexception { InternalError(String message) { super(message); } }
class InTimeAdvancingState extends RTIexception { InTimeAdvancingState(String message) { super(message); } }
class InvalidAttributeHandle extends RTIexception { InvalidAttributeHandle(String message) { super(message); } }
class InvalidCredentials extends RTIexception { InvalidCredentials(String message) { super(message); } }
class InvalidDimensionHandle extends RTIexception { InvalidDimensionHandle(String message) { super(message); } }
class InvalidFederateHandle extends RTIexception { InvalidFederateHandle(String message) { super(message); } }
class InvalidFOM extends RTIexception { InvalidFOM(String message) { super(message); } }
class InvalidInteractionClassHandle extends RTIexception { InvalidInteractionClassHandle(String message) { super(message); } }
class InvalidLogicalTime extends RTIexception { InvalidLogicalTime(String message) { super(message); } }
class InvalidLogicalTimeInterval extends RTIexception { InvalidLogicalTimeInterval(String message) { super(message); } }
class InvalidLookahead extends RTIexception { InvalidLookahead(String message) { super(message); } }
class InvalidMessageRetractionHandle extends RTIexception { InvalidMessageRetractionHandle(String message) { super(message); } }
class InvalidMIM extends RTIexception { InvalidMIM(String message) { super(message); } }
class InvalidObjectClassHandle extends RTIexception { InvalidObjectClassHandle(String message) { super(message); } }
class InvalidObjectInstanceHandle extends RTIexception { InvalidObjectInstanceHandle(String message) { super(message); } }
class InvalidOrderName extends RTIexception { InvalidOrderName(String message) { super(message); } }
class InvalidOrderType extends RTIexception { InvalidOrderType(String message) { super(message); } }
class InvalidParameterHandle extends RTIexception { InvalidParameterHandle(String message) { super(message); } }
class InvalidRangeBound extends RTIexception { InvalidRangeBound(String message) { super(message); } }
class InvalidRegion extends RTIexception { InvalidRegion(String message) { super(message); } }
class InvalidRegionContext extends RTIexception { InvalidRegionContext(String message) { super(message); } }
class InvalidResignAction extends RTIexception { InvalidResignAction(String message) { super(message); } }
class InvalidServiceGroup extends RTIexception { InvalidServiceGroup(String message) { super(message); } }
class InvalidTransportationName extends RTIexception { InvalidTransportationName(String message) { super(message); } }
class InvalidTransportationTypeHandle extends RTIexception { InvalidTransportationTypeHandle(String message) { super(message); } }
class InvalidUpdateRateDesignator extends RTIexception { InvalidUpdateRateDesignator(String message) { super(message); } }
class LogicalTimeAlreadyPassed extends RTIexception { LogicalTimeAlreadyPassed(String message) { super(message); } }
class MessageCanNoLongerBeRetracted extends RTIexception { MessageCanNoLongerBeRetracted(String message) { super(message); } }
class NameNotFound extends RTIexception { NameNotFound(String message) { super(message); } }
class NameSetWasEmpty extends RTIexception { NameSetWasEmpty(String message) { super(message); } }
class NoAcquisitionPending extends RTIexception { NoAcquisitionPending(String message) { super(message); } }
class ObjectClassNotDefined extends RTIexception { ObjectClassNotDefined(String message) { super(message); } }
class ObjectClassNotPublished extends RTIexception { ObjectClassNotPublished(String message) { super(message); } }
class ObjectClassRelevanceAdvisorySwitchIsOff extends RTIexception { ObjectClassRelevanceAdvisorySwitchIsOff(String message) { super(message); } }
class ObjectClassRelevanceAdvisorySwitchIsOn extends RTIexception { ObjectClassRelevanceAdvisorySwitchIsOn(String message) { super(message); } }
class ObjectInstanceNameInUse extends RTIexception { ObjectInstanceNameInUse(String message) { super(message); } }
class ObjectInstanceNameNotReserved extends RTIexception { ObjectInstanceNameNotReserved(String message) { super(message); } }
class OwnershipAcquisitionPending extends RTIexception { OwnershipAcquisitionPending(String message) { super(message); } }
class RegionDoesNotContainSpecifiedDimension extends RTIexception { RegionDoesNotContainSpecifiedDimension(String message) { super(message); } }
class RegionInUseForUpdateOrSubscription extends RTIexception { RegionInUseForUpdateOrSubscription(String message) { super(message); } }
class RegionNotCreatedByThisFederate extends RTIexception { RegionNotCreatedByThisFederate(String message) { super(message); } }
class ReportServiceInvocationsAreSubscribed extends RTIexception { ReportServiceInvocationsAreSubscribed(String message) { super(message); } }
class RequestForTimeConstrainedPending extends RTIexception { RequestForTimeConstrainedPending(String message) { super(message); } }
class RequestForTimeRegulationPending extends RTIexception { RequestForTimeRegulationPending(String message) { super(message); } }
class RestoreInProgress extends RTIexception { RestoreInProgress(String message) { super(message); } }
class RestoreNotInProgress extends RTIexception { RestoreNotInProgress(String message) { super(message); } }
class RestoreNotRequested extends RTIexception { RestoreNotRequested(String message) { super(message); } }
class SaveInProgress extends RTIexception { SaveInProgress(String message) { super(message); } }
class SaveNotInProgress extends RTIexception { SaveNotInProgress(String message) { super(message); } }
class SaveNotInitiated extends RTIexception { SaveNotInitiated(String message) { super(message); } }
class SynchronizationPointLabelNotAnnounced extends RTIexception { SynchronizationPointLabelNotAnnounced(String message) { super(message); } }
class TimeConstrainedAlreadyEnabled extends RTIexception { TimeConstrainedAlreadyEnabled(String message) { super(message); } }
class TimeConstrainedIsNotEnabled extends RTIexception { TimeConstrainedIsNotEnabled(String message) { super(message); } }
class TimeRegulationAlreadyEnabled extends RTIexception { TimeRegulationAlreadyEnabled(String message) { super(message); } }
class TimeRegulationIsNotEnabled extends RTIexception { TimeRegulationIsNotEnabled(String message) { super(message); } }
class Unauthorized extends RTIexception { Unauthorized(String message) { super(message); } }
class UnsupportedCallbackModel extends RTIexception { UnsupportedCallbackModel(String message) { super(message); } }
