#include "ieee1516_2025_federation_management_fixture_support.hpp"

namespace {

TEST_CASE(
    "Embedded MOM HLAmodifyAttributeState changes application ownership without callbacks",
    "[integration][development-profile][federation-management][mom][ownership-management]"
    "[rti.service.send-interaction][rti.service.query-attribute-ownership]"
    "[federate.callback.inform-attribute-ownership]"
    "[federate.callback.attribute-is-not-owned]") {
  ReportingFederateAmbassador ownerReports;
  ReportingFederateAmbassador targetReports;
  auto owner = makeRti();
  auto target = makeRti();
  auto const federationName = nextFederationName();
  auto const fomModule = (std::filesystem::path(UMBRA_SOURCE_DIRECTORY) /
                          "cpp" /
                          "tests" /
                          "data" /
                          "attribute-update-passel-fom.xml")
                             .wstring();

  REQUIRE_NOTHROW(owner->connect(ownerReports, HLA_EVOKED));
  REQUIRE_NOTHROW(target->connect(targetReports, HLA_EVOKED));
  REQUIRE_NOTHROW(
      owner->createFederationExecution(federationName, fomModule, L"HLAinteger64Time"));
  FederateHandle targetFederate;
  REQUIRE_NOTHROW(owner->joinFederationExecution(
      L"mom-modify-owner", L"publisher", federationName));
  REQUIRE_NOTHROW(targetFederate = target->joinFederationExecution(
      L"mom-modify-target", L"publisher", federationName));

  auto const child = owner->getObjectClassHandle(
      L"HLAobjectRoot.UmbraAttributeFixtureBase.UmbraAttributeFixtureChild");
  auto const reliableBaseA = owner->getAttributeHandle(child, L"ReliableBaseA");
  auto const modifyAttributeState = owner->getInteractionClassHandle(
      L"HLAinteractionRoot.HLAmanager.HLAfederate.HLAadjust.HLAmodifyAttributeState");
  auto const federateParameter = owner->getParameterHandle(
      modifyAttributeState,
      L"HLAfederate");
  auto const objectParameter = owner->getParameterHandle(
      modifyAttributeState,
      L"HLAobjectInstance");
  auto const attributeParameter = owner->getParameterHandle(
      modifyAttributeState,
      L"HLAattribute");
  auto const stateParameter = owner->getParameterHandle(
      modifyAttributeState,
      L"HLAattributeState");
  REQUIRE(child.isValid());
  REQUIRE(reliableBaseA.isValid());
  REQUIRE(modifyAttributeState.isValid());
  REQUIRE(federateParameter.isValid());
  REQUIRE(objectParameter.isValid());
  REQUIRE(attributeParameter.isValid());
  REQUIRE(stateParameter.isValid());

  AttributeHandleSet const attributeSet{reliableBaseA};
  REQUIRE_NOTHROW(owner->publishObjectClassAttributes(child, attributeSet));
  REQUIRE_NOTHROW(owner->subscribeObjectClassAttributes(child, attributeSet));
  REQUIRE_NOTHROW(target->subscribeObjectClassAttributes(child, attributeSet));
  REQUIRE_NOTHROW(target->publishObjectClassAttributes(child, attributeSet));
  ObjectInstanceHandle objectInstance;
  REQUIRE_NOTHROW(objectInstance = owner->registerObjectInstance(child));
  REQUIRE_FALSE(target->evokeMultipleCallbacks(0.0, 0.0));
  REQUIRE(targetReports.objectDiscoveryReports.size() == 1U);
  REQUIRE(target->getKnownObjectClassHandle(objectInstance) == child);

  // Establish that the discovering federate's known-instance route can
  // receive the ordinary query callback before the MOM control path changes
  // ownership.
  REQUIRE_NOTHROW(target->queryAttributeOwnership(objectInstance, attributeSet));
  REQUIRE(targetReports.attributeOwnershipReports.empty());
  REQUIRE_FALSE(target->evokeMultipleCallbacks(0.0, 0.0));
  REQUIRE(targetReports.attributeOwnershipReports.size() == 1U);
  REQUIRE(targetReports.attributeOwnershipReports.front().kind ==
          ReportingFederateAmbassador::AttributeOwnershipReport::Kind::federate);
  REQUIRE(targetReports.attributeOwnershipReports.front().owner == owner->getFederateHandle(
      L"mom-modify-owner"));
  targetReports.attributeOwnershipReports.clear();

  auto makeModifyValues = [&](bool owned) {
    return ParameterHandleValueMap{
        {federateParameter, targetFederate.encode()},
        {objectParameter, objectInstance.encode()},
        {attributeParameter, reliableBaseA.encode()},
        {stateParameter, rti1516_2025::HLAinteger32BE{owned ? 1 : 0}.encode()},
    };
  };
  auto sendModify = [&](bool owned) {
    REQUIRE_NOTHROW(owner->sendInteraction(
        modifyAttributeState,
        makeModifyValues(owned),
        VariableLengthData()));
  };

  // The target must be publishing before the MOM interaction can assign
  // ownership.  No acquisition/release callback is generated by this direct
  // control path.
  sendModify(true);
  REQUIRE_FALSE(owner->isAttributeOwnedByFederate(objectInstance, reliableBaseA));
  REQUIRE(target->isAttributeOwnedByFederate(objectInstance, reliableBaseA));
  REQUIRE(ownerReports.attributeOwnershipAcquisitionReports.empty());
  REQUIRE(targetReports.attributeOwnershipAcquisitionReports.empty());
  REQUIRE_NOTHROW(target->queryAttributeOwnership(objectInstance, attributeSet));
  REQUIRE(targetReports.attributeOwnershipReports.empty());
  REQUIRE_FALSE(target->evokeMultipleCallbacks(0.0, 0.0));
  REQUIRE(targetReports.attributeOwnershipReports.size() == 1U);
  REQUIRE(targetReports.attributeOwnershipReports.front().kind ==
          ReportingFederateAmbassador::AttributeOwnershipReport::Kind::federate);
  REQUIRE(targetReports.attributeOwnershipReports.front().owner == targetFederate);
  targetReports.attributeOwnershipReports.clear();

  // Unowned is a direct state transition and does not require the target to
  // retain publication.  The subsequent query therefore reports the standard
  // Attribute Is Not Owned callback.
  sendModify(false);
  REQUIRE(ownerReports.attributeOwnershipAcquisitionReports.empty());
  REQUIRE(targetReports.attributeOwnershipAcquisitionReports.empty());
  REQUIRE_NOTHROW(target->queryAttributeOwnership(objectInstance, attributeSet));
  REQUIRE(targetReports.attributeOwnershipReports.empty());
  REQUIRE_FALSE(target->evokeMultipleCallbacks(0.0, 0.0));
  REQUIRE(targetReports.attributeOwnershipReports.size() == 1U);
  REQUIRE(targetReports.attributeOwnershipReports.front().kind ==
          ReportingFederateAmbassador::AttributeOwnershipReport::Kind::unowned);
  targetReports.attributeOwnershipReports.clear();

  // Assignment to Owned is rejected without changing state when the target
  // is no longer publishing the corresponding class attribute. Restore the
  // declaration before exercising the successful re-assignment below.
  REQUIRE_NOTHROW(target->unpublishObjectClassAttributes(child, attributeSet));
  REQUIRE_THROWS_AS(
      owner->sendInteraction(
          modifyAttributeState,
          makeModifyValues(true),
          VariableLengthData()),
      rti1516_2025::AttributeNotPublished);
  REQUIRE_NOTHROW(target->publishObjectClassAttributes(child, attributeSet));

  // The same interaction can immediately assign the attribute again; no
  // ownership-notification callback is synthesized for either transition.
  sendModify(true);
  REQUIRE(ownerReports.attributeOwnershipAcquisitionReports.empty());
  REQUIRE(targetReports.attributeOwnershipAcquisitionReports.empty());

  // A predefined MOM attribute is RTI-owned and must never be routed through
  // the application ownership ledger.  The private snapshot is used only to
  // obtain the internal object handle for this negative boundary test.
  auto* ownerUmbra = dynamic_cast<rti1516_2025::umbra_binding_detail::UmbraRtiAmbassador*>(
      owner.get());
  REQUIRE(ownerUmbra != nullptr);
  auto const momSnapshot = ownerUmbra->joinedFederateMomObjectSnapshotForTesting();
  REQUIRE(momSnapshot);
  auto const momClass = owner->getObjectClassHandle(
      L"HLAobjectRoot.HLAmanager.HLAfederate");
  auto const momAttribute = owner->getAttributeHandle(momClass, L"HLAfederateName");
  REQUIRE(momClass.isValid());
  REQUIRE(momAttribute.isValid());
  REQUIRE_THROWS_AS(
      owner->sendInteraction(
          modifyAttributeState,
          ParameterHandleValueMap{
              {federateParameter, targetFederate.encode()},
              {objectParameter,
               rti1516_2025::umbra_binding_detail::makeObjectInstanceHandle(
                   momSnapshot->objectInstanceHandle)
                   .encode()},
              {attributeParameter, momAttribute.encode()},
              {stateParameter, rti1516_2025::HLAinteger32BE{1}.encode()},
          },
          VariableLengthData()),
      rti1516_2025::RTIinternalError);

  REQUIRE_NOTHROW(target->resignFederationExecution(CANCEL_THEN_DELETE_THEN_DIVEST));
  REQUIRE_NOTHROW(owner->resignFederationExecution(CANCEL_THEN_DELETE_THEN_DIVEST));
  REQUIRE_NOTHROW(owner->destroyFederationExecution(federationName));
  REQUIRE_NOTHROW(target->disconnect());
  REQUIRE_NOTHROW(owner->disconnect());
}

} // namespace
