"""Generate the bounded IEEE 1516e-2010 C++ ambassador shell.

The official header is the source of truth. Every pure virtual
``RTIambassador`` service is copied into a concrete private class. A small
provider-owned reference slice covers federation membership, declaration
lookup/publication, object registration/update callbacks, and interaction
publish/subscribe/send callbacks; all remaining services continue to throw
``RTIinternalError`` until their own gate exists.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HEADER = ROOT / "third_party" / "ieee1516.1-2010" / "include" / "RTI" / "RTIambassador.h"
DEFAULT_OUTPUT = ROOT / "cpp" / "generated" / "rti_ambassador_shell_2010.hpp"


def _declarations(header: Path) -> list[str]:
    source = header.read_text(encoding="utf-8")
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    source = re.sub(r"//[^\r\n]*", "", source)
    declarations: list[str] = []
    for part in source.split(";"):
        if "virtual" not in part or not re.search(r"=\s*0\s*$", part):
            continue
        start = part.rfind("virtual")
        declaration = part[start:]
        declaration = re.sub(r"\s*=\s*0\s*$", "", declaration)
        declaration = re.sub(r"\s+", " ", declaration).strip()
        if not declaration.startswith("virtual "):
            raise ValueError(f"unexpected pure virtual declaration: {declaration}")
        declarations.append(declaration.removeprefix("virtual "))
    if len(declarations) != 151:
        raise ValueError(f"expected 151 pure virtual services, found {len(declarations)}")
    return declarations


def _render(declarations: list[str]) -> str:
    body = [
        "// Generated by tools/generate_1516e_cpp_shell.py; do not edit by hand.",
        "// Federation/declaration/object/interaction services use the bounded",
        "// reference slice; all other IEEE 1516.1-2010 services intentionally throw.",
        "#pragma once",
        "",
        "#include <RTI/RTI1516.h>",
        "#include \"internal/runtime/reference_2010.hpp\"",
        "",
        "namespace rti1516e {",
        "namespace umbra_binding_detail {",
        "",
        "class RtiAmbassadorShell final : public rti1516e::RTIambassador {",
        " public:",
        "  RtiAmbassadorShell() throw() : connected_(false), joined_(false), federateAmbassador_(nullptr) {}",
        "  ~RtiAmbassadorShell() throw() override = default;",
        "",
    ]
    for declaration in declarations:
        if declaration.startswith("void connect ("):
            body.extend(
                (
                    f"  {declaration} override {{",
                    "    if (connected_) {",
                    "      throw AlreadyConnected(L\"Umbra IEEE 1516.1-2010 binding is already connected.\");",
                    "    }",
                    "    connected_ = true;",
                    "    federateAmbassador_ = &federateAmbassador;",
                    "    callbackModel_ = theCallbackModel;",
                    "  }",
                    "",
                )
            )
            continue
        if declaration.startswith("void disconnect ("):
            body.extend(
                (
                    f"  {declaration} override {{",
                    "    if (!connected_) {",
                    "      // The official 2010 C++ disconnect declaration does not",
                    "      // permit NotConnected in its exception specification.",
                    "      throw RTIinternalError(L\"Umbra IEEE 1516.1-2010 binding is not connected.\");",
                    "    }",
                    "    if (joined_) {",
                    "      umbra_binding_detail::ReferenceRuntime2010::instance().disconnect(this);",
                    "      throw FederateIsExecutionMember(L\"A federate must resign before disconnecting.\");",
                    "    }",
                    "    connected_ = false;",
                    "    federateAmbassador_ = nullptr;",
                    "  }",
                    "",
                )
            )
            continue
        if declaration.startswith("void createFederationExecution ("):
            if "std::vector" in declaration:
                body.extend((
                    f"  {declaration} override {{",
                    "    requireConnected();",
                    "    umbra_binding_detail::ReferenceRuntime2010::instance().createFederation(federationExecutionName);",
                    "  }",
                    "",
                ))
            else:
                body.extend((
                    f"  {declaration} override {{",
                    "    requireConnected();",
                    "    umbra_binding_detail::ReferenceRuntime2010::instance().createFederation(federationExecutionName);",
                    "  }",
                    "",
                ))
            continue
        if declaration.startswith("void createFederationExecutionWithMIM ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().createFederation(federationExecutionName);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void destroyFederationExecution ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().destroyFederation(federationExecutionName);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void listFederationExecutions ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().listFederations(*federateAmbassador_);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("FederateHandle joinFederationExecution ("):
            if "federateName" in declaration:
                body.extend((
                    f"  {declaration} override {{",
                    "    requireConnected();",
                    "    federateHandle_ = umbra_binding_detail::ReferenceRuntime2010::instance().join(this, *federateAmbassador_, federateName, federateType, federationExecutionName);",
                    "    joined_ = true;",
                    "    return federateHandle_;",
                    "  }",
                    "",
                ))
            else:
                body.extend((
                    f"  {declaration} override {{",
                    "    requireConnected();",
                    "    federateHandle_ = umbra_binding_detail::ReferenceRuntime2010::instance().join(this, *federateAmbassador_, L\"\", federateType, federationExecutionName);",
                    "    joined_ = true;",
                    "    return federateHandle_;",
                    "  }",
                    "",
                ))
            continue
        if declaration.startswith("void registerFederationSynchronizationPoint ("):
            if "FederateHandleSet" in declaration:
                body.extend((
                    f"  {declaration} override {{",
                    "    requireConnected();",
                    "    umbra_binding_detail::ReferenceRuntime2010::instance().registerFederationSynchronizationPoint(this, label, theUserSuppliedTag, synchronizationSet);",
                    "  }",
                    "",
                ))
            else:
                body.extend((
                    f"  {declaration} override {{",
                    "    requireConnected();",
                    "    umbra_binding_detail::ReferenceRuntime2010::instance().registerFederationSynchronizationPoint(this, label, theUserSuppliedTag);",
                    "  }",
                    "",
                ))
            continue
        if declaration.startswith("void synchronizationPointAchieved ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().synchronizationPointAchieved(this, label, successfully);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void resignFederationExecution ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().resign(this, resignAction);",
                "    joined_ = false;",
                "    federateHandle_ = FederateHandle();",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void publishObjectClassAttributes ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().publishObjectClassAttributes(this, theClass, attributeList);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void unpublishObjectClassAttributes ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().unpublishObjectClassAttributes(this, theClass, attributeList);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void unpublishObjectClass ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().unpublishObjectClass(this, theClass);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void publishInteractionClass ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().publishInteractionClass(this, theInteraction);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void unpublishInteractionClass ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().unpublishInteractionClass(this, theInteraction);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void subscribeObjectClassAttributes ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().subscribeObjectClassAttributes(this, theClass, attributeList);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void unsubscribeObjectClassAttributes ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().unsubscribeObjectClassAttributes(this, theClass, attributeList);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void unsubscribeObjectClass ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().unsubscribeObjectClass(this, theClass);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void subscribeInteractionClass ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().subscribeInteractionClass(this, theClass);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void unsubscribeInteractionClass ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().unsubscribeInteractionClass(this, theClass);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("ObjectInstanceHandle registerObjectInstance ("):
            if "std::wstring const" in declaration:
                body.extend((
                    f"  {declaration} override {{",
                    "    requireConnected();",
                    "    return umbra_binding_detail::ReferenceRuntime2010::instance().registerObjectInstance(this, theClass, &theObjectInstanceName);",
                    "  }",
                    "",
                ))
            else:
                body.extend((
                    f"  {declaration} override {{",
                    "    requireConnected();",
                    "    return umbra_binding_detail::ReferenceRuntime2010::instance().registerObjectInstance(this, theClass, nullptr);",
                    "  }",
                    "",
                ))
            continue
        if declaration.startswith("void updateAttributeValues (") and "LogicalTime const" not in declaration:
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().updateAttributeValues(this, theObject, theAttributeValues, theUserSuppliedTag);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void sendInteraction (") and "LogicalTime const" not in declaration:
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().sendInteraction(this, theInteraction, theParameterValues, theUserSuppliedTag);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("void queryAttributeOwnership ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    umbra_binding_detail::ReferenceRuntime2010::instance().queryAttributeOwnership(this, theObject, theAttribute);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("bool isAttributeOwnedByFederate ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().isAttributeOwnedByFederate(this, theObject, theAttribute);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("ObjectClassHandle getObjectClassHandle ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getObjectClassHandle(this, theName);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("FederateHandle getFederateHandle ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getFederateHandle(this, theName);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("std::wstring getFederateName ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getFederateName(this, theHandle);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("std::wstring getObjectClassName ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getObjectClassName(this, theHandle);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("std::wstring getObjectInstanceName ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getObjectInstanceName(this, theHandle);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("AttributeHandle getAttributeHandle ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getAttributeHandle(this, whichClass, theAttributeName);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("std::wstring getAttributeName ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getAttributeName(this, whichClass, theHandle);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("InteractionClassHandle getInteractionClassHandle ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getInteractionClassHandle(this, theName);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("std::wstring getInteractionClassName ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getInteractionClassName(this, theHandle);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("ParameterHandle getParameterHandle ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getParameterHandle(this, whichClass, theName);",
                "  }",
                "",
            ))
            continue
        if declaration.startswith("std::wstring getParameterName ("):
            body.extend((
                f"  {declaration} override {{",
                "    requireConnected();",
                "    return umbra_binding_detail::ReferenceRuntime2010::instance().getParameterName(this, whichClass, theHandle);",
                "  }",
                "",
            ))
            continue
        body.extend(
            (
                f"  {declaration} override {{",
                "    unavailable();",
                "  }",
                "",
            )
        )
    body.extend(
        (
            " private:",
            "  bool connected_;",
            "  bool joined_;",
            "  FederateAmbassador* federateAmbassador_;",
            "  FederateHandle federateHandle_;",
            "  CallbackModel callbackModel_ = HLA_IMMEDIATE;",
            "",
            "  void requireConnected() const throw (NotConnected) {",
            "    if (!connected_) throw NotConnected(L\"The IEEE 1516.1-2010 shell is not connected.\");",
            "  }",
            "",
            "  [[noreturn]] static void unavailable() throw (RTIinternalError) {",
            "    throw RTIinternalError(",
            "        L\"Umbra's IEEE 1516.1-2010 C++ binding does not implement this service.\");",
            "  }",
            "};",
            "",
        "}  // namespace umbra_binding_detail",
        "}  // namespace rti1516e",
            "",
        )
    )
    return "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        expected = _render(_declarations(args.header.resolve()))
        output = args.output.resolve()
        if args.check:
            if output.read_text(encoding="utf-8") != expected:
                print("IEEE 1516e C++ shell drifted", file=sys.stderr)
                return 1
            print("IEEE 1516e C++ bounded shell: PASS (151 service overrides)")
            return 0
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8")
        print(f"wrote IEEE 1516e C++ reference shell to {output}")
        return 0
    except (OSError, ValueError) as error:
        print(f"IEEE 1516e C++ bounded shell: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
