"""Generate the private fallback base for Umbra's standard RTI ambassador.

The generated class supplies a visible, reviewable fallback implementation for
every IEEE pure virtual RTI ambassador member. A real Umbra vertical slice may
override an exact standard member in a derived private class; every member it
does not override throws ``RTIinternalError``. The fallback itself is never
service or conformance evidence.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INVENTORY = REPOSITORY_ROOT / "compliance" / "standards" / "binding-inventory.json"
DEFAULT_OUTPUT = REPOSITORY_ROOT / "cpp" / "generated" / "rti_ambassador_shell.hpp"
_RTI_AMBASSADOR = "rti1516_2025::RTIambassador"


def _inventory_members(path: Path) -> list[dict[str, str]]:
    try:
        inventory: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read binding inventory: {error}") from error
    classes = inventory.get("classes")
    if inventory.get("schema_version") != 1 or not isinstance(classes, list):
        raise ValueError("binding inventory has an unsupported shape")
    matches = [item for item in classes if isinstance(item, dict) and item.get("class") == _RTI_AMBASSADOR]
    if len(matches) != 1:
        raise ValueError("binding inventory must contain exactly one RTIambassador entry")
    members = matches[0].get("members")
    if not isinstance(members, list) or len(members) != 181:
        raise ValueError("binding inventory must contain 181 RTIambassador members")
    result: list[dict[str, str]] = []
    for member in members:
        if not isinstance(member, dict):
            raise ValueError("binding inventory contains an invalid member")
        name = member.get("name")
        signature = member.get("signature")
        if not isinstance(name, str) or not isinstance(signature, str):
            raise ValueError("binding inventory member is missing name or signature")
        result.append({"name": name, "signature": signature})
    return result


def _render(members: list[dict[str, str]]) -> str:
    body: list[str] = [
        "// Generated by tools/generate_rti_ambassador_shell.py; do not edit by hand.",
        "// This private fallback throws RTIinternalError for every service not overridden by a real Umbra slice.",
        "#pragma once",
        "",
        "#include <RTI/RTI1516.h>",
        "",
        "namespace rti1516_2025::umbra_binding_detail {",
        "",
        "class RtiAmbassadorShell : public rti1516_2025::RTIambassador {",
        " public:",
        "  RtiAmbassadorShell() = default;",
        "  ~RtiAmbassadorShell() override = default;",
        "",
    ]
    for member in members:
        body.extend(
            (
                f"  {member['signature']} override {{",
                "    unavailable();",
                "  }",
                "",
            )
        )
    body.extend(
        (
            " private:",
            "  [[noreturn]] static void unavailable() {",
            "    throw RTIinternalError(",
            "        L\"Umbra's IEEE 1516.1-2025 C++ binding shell does not implement this service.\");",
            "  }",
            "};",
            "",
            "}  // namespace rti1516_2025::umbra_binding_detail",
            "",
        )
    )
    return "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", type=Path, default=DEFAULT_INVENTORY)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail if the generated shell drifts")
    args = parser.parse_args()
    try:
        expected = _render(_inventory_members(args.inventory.resolve()))
        output = args.output.resolve()
        if args.check:
            if output.read_text(encoding="utf-8") != expected:
                print("RTI ambassador shell drifted: regenerate it from the binding inventory", file=sys.stderr)
                return 1
            print("RTI ambassador binding shell: PASS (181 fallback service overrides)")
            return 0
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8")
        print(f"wrote RTI ambassador binding shell to {output}")
        return 0
    except (OSError, ValueError) as error:
        print(f"RTI ambassador shell: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
