target_sources(umbra_rti PRIVATE
  cpp/src/internal/runtime/umbra_rti_ambassador_dimension_region_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_request_attribute_value_updates.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_time_advance_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_time_advance_dispatch.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_time_bounds_lookahead.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_ownership_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_ownership_callback_dispatch.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_order_transportation_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_periodic_mom_scheduler.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_object_instance_lookup.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_advisory_switches.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_support_switches.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_federate_identity_lookup.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_object_instance_lifecycle_callbacks.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_interaction_callbacks.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_interaction_declaration_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_interaction_subscription_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_interaction_send_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_interaction_send_mom_controls.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_timestamped_interaction_send.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_directed_interaction_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_object_deletion_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_attribute_update_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_callback_control_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_mom_synchronization_reports.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_mom_object_instance_reports.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_mom_activity_reports.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_mom_declaration_reports.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_mom_fom_module_reports.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_service_report_writers.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_membership_loss.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_federation_lifecycle.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_handle_normalization.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_public_handle_decoding.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_regional_interaction_subscription.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_regional_interaction_send_services.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_asynchronous_delivery.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_tso_receive_order_interaction.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_synchronization_notification_dispatch.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_save_restore_notifications.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_retract_service.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_mom_service_report_interaction.cpp
  cpp/src/internal/runtime/umbra_rti_ambassador_connect_services.cpp
  cpp/src/internal/runtime/ambassador_connection_support.cpp
)
